version: '3'
services:
  bokeh:
    build: ./scripts/
    ports:
        - "8889:8889"
    environment:
      - REDIS_PORT=6379
      - REDIS_URL=redis
    volumes:
      - ./:/app
    depends_on:
      - redis
      - game_of_life
  game_of_life:
    build: ./
    environment:
      - REDIS_PORT=6379
      - REDIS_URL=redis
    depends_on:
      - redis
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
